name: CI

on: push

jobs:
  pylint:
    runs-on: ubuntu-latest
    container: fringelid/ifc_data_checker_ci
    steps:
      - uses: actions/checkout@v2
      - name: Print job pylint
        run: echo pylint
      - name: Do pylint
        run: pylint ./ifc_data_checker/
      - name: Upload pylint artifact
        uses: actions/upload-artifact@v2
        with:
          name: source code
          path: ./ifc_data_checker/
  
  bandit:
    runs-on: ubuntu-latest
    container: fringelid/ifc_data_checker_ci
    steps:
      - uses: actions/checkout@v2
      - name: Print job bandit
        run: echo bandit
      - name: Do bandit
        run: bandit -r . -x ./ifcopenshell/ -o bandit-report.txt -f txt
      - name: Upload bandit artifact
        uses: actions/upload-artifact@v2
        with:
          name: bandit report
          path: ./bandit-report.txt
